project_name = "New Project"
version = { major = 0, minor = 0, patch = 1 }
renderer_settings = { texture_compression = "BC", generate_mips = true, max_texture_size = 4096, colour_space = "sRGB", mesh_vertex_cache_reordering = true, mesh_triangle_stripification = false, lod_count = 4, lod_simplification = 0.5, oct_encoded_normals = true, vertex_quant_position = "F32", vertex_quant_uv = "F32", vertex_quant_tangent = "F32", index_buffer_format = "U32", anim_quant_rotation = "U16", anim_quant_translation = "U16", anim_quant_scale = "U8", bone_weight_format = "U8" }
spatial_settings = { cubic = false, chunk_size = 16, cell_size = 4 }

[[modules]]
name = "BF_GPU"
enabled = true
required = true
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_DAG"
enabled = true
required = true
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_ECS"
enabled = true
required = true
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_REP"
enabled = false
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_Input"
enabled = true
required = true
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_Miniaudio"
enabled = false
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_Box3D_Physics"
enabled = false
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "ATLAS-RMGUI"
enabled = false
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_Scripting"
enabled = false
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_Editor"
enabled = false
version = { major = 0, minor = 0, patch = 1 }
[[modules]]
name = "BF_ENet"
enabled = false
version = { major = 0, minor = 0, patch = 1 }

[[extensions]]
name = "BF_GPU_Mesh"
enabled = false
version = { major = 0, minor = 0, patch = 1 }

[[plugins]]
name = "Example Plugin"
enabled = false
version = { major = 0, minor = 0, patch = 1 }
